config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  #login -> new session
  #logout -> close session
  #post login -> create session
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
  
end


#get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as:  'new_recipe'
  #post '/recipes', to: 'recipes#create'
  #get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch '/recipes/:id', to: 'recipes#update'
  #get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  #delete '/recipes/:id', to: 'recipes#destroy'

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to my receipes app</h1>
    <h2>This is the home page to the Ruby on Rails Development course</h2>
    
    <%= link_to "Sign Up Now", register_path , class: "btn btn-lg btn-success" %>
</div>
<div class="row">
    <div class="col-lg-4">
        <h3 class="midrow">View Receipes as guest user</h3>
        <h2 class="left">Browse and view receipes as a guest and Sign Up later</h2>
        <p><%= link_to "Browse receipe listing", recipes_path, class: "btn btn-warning btn-small" %> </p>
    </div>
    <div class="col-lg-4">
        <h3 class="midrow">Sign in to your account</h3>
        <h2 class="left">Add/Update your receipes/create reviews/like-disklike</h2>
        <p><%= link_to "Log In", login_path, class: "btn btn-warning btn-small" %> </p>
    </div>
    <div class="col-lg-4">
        <h3 class="midrow">View Receipes as guest user</h3>
        <h2 class="left">Browse and view receipes as a guest and Sign Up later</h2>
        <p><%= link_to "Browse receipe listing", "", class: "btn btn-warning btn-small" %> </p>
    </div>
</div>
<div class=''>
    
</div>